### ISSUE TITLE
MMM-Snow does not have a start function

### ISSUE THREAD

**Issue by stanchanpsu** [MichMich/MMM-Snow#1]
Am I mistaken that this module is not finished yet? The MMM-Snow.js file doesn't have a start function and keeps the MM from loading when I import it.

**Comment by MichMich** [comment]
A module doesn't need a start function. If there isn't a start method, it uses the start method of the superclass.

What error do you get?

**Comment by stanchanpsu** [comment]
I actually solved my issue:

This, like some other issues I was running into was actually caused by the application freezing when it could not load ‘css/custom.css’.
This is because the .gitignore does not track custom.css and I, like many others, edit my code on my desktop and then push the changes via git to my RPi.

Do you think there should be changes to throw an error if custom.css is not found? Or to skip the file altogether if it doesn't exist?

**Comment by MichMich** [comment]
Indeed, custom.css could just be skipped if it isn't found. Feel free to send a PR.
